version: 2.1

jobs:
  build:
    docker:
      - image: cgr.dev/chainguard/bash:latest
    steps:
      - checkout
      - run:
          name: Run Bash Script
          command: |
            echo "Hello, World!"
            bash -version
            uname -a
