version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  snapshot-directory:
    executor: docker-executor
    environment:
      IMAGE_NAME: petesimage 
    steps:
      - run:
          name: Say Hello
          command: echo "Hello World"
      - checkout
      - run:
          name: List /usr directory
          command: |
            ls -l /usr > usr_contents.txt
      - run:
          name: List /usr/lib directory
          command: |
            ls -l /usr/lib > usr_lib_contents.txt
      - run:
          name: Combine Directory Listings
          command: |
            cat usr_contents.txt usr_lib_contents.txt > combined_directory_contents.txt
      - persist_to_workspace:
          root: .
          paths:
            - combined_directory_contents.txt
      - store_artifacts:
          path: combined_directory_contents.txt
          destination: directory_snapshots
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - run:
          name: Run Security Scan
          command: |
            ./trivy image --severity CRITICAL,HIGH $IMAGE_NAME

workflows:
  version: 2
  snapshot_and_view:
    jobs:
      - snapshot-directory
