version: 2.1
jobs:
  build:
    docker:
     - image: cimg/postgres:17.3.0
    resource_class: petez7519/aws_runner
    steps:
     - run:
         name: Pull Docker Image
         command: docker pull cimg/postgres:17.3.0
     - run: echo "Hi I'm on a Container Runner!"
workflows:
  build-workflow:
    jobs:
      - build
